table Accounts
	lineageTag: 0e8b118e-acd6-469b-89c9-75a437eec02f

	measure 'New Companies (<10 Years)' = ```
			
			CALCULATE(
			    COUNTROWS('Accounts'),
			    'Accounts'[Year Established] >= YEAR(TODAY()) - 10
			)
			
			```
		formatString: 0
		lineageTag: b95b3043-1e11-43c8-85e4-db93bd73bc5a

	column Account
		dataType: string
		lineageTag: c883b7f5-deb8-4fbf-9e1d-7aae4e1ef4a1
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: e63586de-2f53-4546-a2b3-11a98e1db189
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column 'Year Established'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f582280-b164-4a92-9230-3933fbd6c692
		summarizeBy: none
		sourceColumn: Year Established

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Revenue
		dataType: decimal
		lineageTag: 9f3cd654-2aee-4390-9a5d-9804c5e87acd
		summarizeBy: none
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Employees
		dataType: int64
		formatString: 0
		lineageTag: b5bfa576-6d50-4894-8cec-99f9b28bdf21
		summarizeBy: none
		sourceColumn: Employees

		annotation SummarizationSetBy = Automatic

	column 'Office Llocation'
		dataType: string
		lineageTag: 513239e5-0025-4ee4-b808-03a0b607c6a9
		summarizeBy: none
		sourceColumn: Office Llocation

		annotation SummarizationSetBy = Automatic

	column 'Subsidiary of'
		dataType: string
		lineageTag: b6b0660a-8781-404f-a448-95c7e06629ee
		summarizeBy: none
		sourceColumn: Subsidiary of

		annotation SummarizationSetBy = Automatic

	partition Accounts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\data c\Data Analysis Projects Files\My Projects (Excel - Power bi)\CRM & Sales Analytisc\CRM+Sales+Opportunities\accounts.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"account", type text}, {"sector", type text}, {"year_established", Int64.Type}, {"revenue", type number}, {"employees", Int64.Type}, {"office_location", type text}, {"subsidiary_of", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"account", "Account"}, {"sector", "Sector"}, {"year_established", "Year Established"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Year Established", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"revenue", "Revenue"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Revenue", Currency.Type}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type2",{{"employees", "Employees"}, {"office_location", "Office Llocation"}, {"subsidiary_of", "Subsidiary of"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns2",{{"Account", Text.Trim, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Trimmed Text", each true)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

